 const TableData = [
  {
    id: 1,
    Bug: "Malcolm",
    Project: "Reynolds",
    Milestone: "Mal, Cap'n",
    Feature: "Access Roles",
    Testing_Type: "Functional Testing",
    Issue_Type: "New Bug",
    Ticket_ID: "XP 260",
    Developer_Name: "John Wick",
    Bug_Type: "Frontend UI",
    Bug_Sub_Type: "Fonts Size",
    Bug_Feedback: "This is Bug Feedback",
    Step_to_Reproduce: "This is Step A -> Set B",
    Ideal_Behavior: "ideal behavior",
  },
  {
    id: 2,
    Bug: "Malcolm",
    Project: "Reynolds",
    Milestone: "Mal, Cap'n",
    Feature: "Access Roles",
    Testing_Type: "Functional Testing",
    Issue_Type: "New Bug",
    Ticket_ID: "XP 260",
    Developer_Name: "John Wick",
    Bug_Type: "Frontend UI",
    Bug_Sub_Type: "Fonts Size",
    Bug_Feedback: "This is Bug Feedback",
    Step_to_Reproduce: "This is Step A -> Set B",
    Ideal_Behavior: "ideal behavior",
  },
  {
    id: 3,
    Bug: "Malcolm",
    Project: "Reynolds",
    Milestone: "Mal, Cap'n",
    Feature: "Access Roles",
    Testing_Type: "Functional Testing",
    Issue_Type: "New Bug",
    Ticket_ID: "XP 260",
    Developer_Name: "John Wick",
    Bug_Type: "Frontend UI",
    Bug_Sub_Type: "Fonts Size",
    Bug_Feedback: "This is Bug Feedback",
    Step_to_Reproduce: "This is Step A -> Set B",
    Ideal_Behavior: "ideal behavior",
  },
  {
    id: 4,
    Bug: "Malcolm",
    Project: "Reynolds",
    Milestone: "Mal, Cap'n",
    Feature: "Access Roles",
    Testing_Type: "Functional Testing",
    Issue_Type: "New Bug",
    Ticket_ID: "XP 260",
    Developer_Name: "John Wick",
    Bug_Type: "Frontend UI",
    Bug_Sub_Type: "Fonts Size",
    Bug_Feedback: "This is Bug Feedback",
    Step_to_Reproduce: "This is Step A -> Set B",
    Ideal_Behavior: "ideal behavior",
  },
  {
    id: 5,
    Bug: "Malcolm",
    Project: "Reynolds",
    Milestone: "Mal, Cap'n",
    Feature: "Access Roles",
    Testing_Type: "Functional Testing",
    Issue_Type: "New Bug",
    Ticket_ID: "XP 260",
    Developer_Name: "John Wick",
    Bug_Type: "Frontend UI",
    Bug_Sub_Type: "Fonts Size",
    Bug_Feedback: "This is Bug Feedback",
    Step_to_Reproduce: "This is Step A -> Set B",
    Ideal_Behavior: "ideal behavior",
  },
  {
    id: 6,
    Bug: "Malcolm",
    Project: "Reynolds",
    Milestone: "Mal, Cap'n",
    Feature: "Access Roles",
    Testing_Type: "Functional Testing",
    Issue_Type: "New Bug",
    Ticket_ID: "XP 260",
    Developer_Name: "John Wick",
    Bug_Type: "Frontend UI",
    Bug_Sub_Type: "Fonts Size",
    Bug_Feedback: "This is Bug Feedback",
    Step_to_Reproduce: "This is Step A -> Set B",
    Ideal_Behavior: "ideal behavior",
  },
  {
    id: 7,
    Bug: "Malcolm",
    Project: "Reynolds",
    Milestone: "Mal, Cap'n",
    Feature: "Access Roles",
    Testing_Type: "Functional Testing",
    Issue_Type: "New Bug",
    Ticket_ID: "XP 260",
    Developer_Name: "John Wick",
    Bug_Type: "Frontend UI",
    Bug_Sub_Type: "Fonts Size",
    Bug_Feedback: "This is Bug Feedback",
    Step_to_Reproduce: "This is Step A -> Set B",
    Ideal_Behavior: "ideal behavior",
  },
  {
    id: 8,
    Bug: "Malcolm",
    Project: "Reynolds",
    Milestone: "Mal, Cap'n",
    Feature: "Access Roles",
    Testing_Type: "Functional Testing",
    Issue_Type: "New Bug",
    Ticket_ID: "XP 260",
    Developer_Name: "John Wick",
    Bug_Type: "Frontend UI",
    Bug_Sub_Type: "Fonts Size",
    Bug_Feedback: "This is Bug Feedback",
    Step_to_Reproduce: "This is Step A -> Set B",
    Ideal_Behavior: "ideal behavior",
  },
  {
    id: 9,
    Bug: "Malcolm",
    Project: "Reynolds",
    Milestone: "Mal, Cap'n",
    Feature: "Access Roles",
    Testing_Type: "Functional Testing",
    Issue_Type: "New Bug",
    Ticket_ID: "XP 260",
    Developer_Name: "John Wick",
    Bug_Type: "Frontend UI",
    Bug_Sub_Type: "Fonts Size",
    Bug_Feedback: "This is Bug Feedback",
    Step_to_Reproduce: "This is Step A -> Set B",
    Ideal_Behavior: "ideal behavior",
  },
  {
    id: 10,
    Bug: "Malcolm",
    Project: "Reynolds",
    Milestone: "Mal, Cap'n",
    Feature: "Access Roles",
    Testing_Type: "Functional Testing",
    Issue_Type: "New Bug",
    Ticket_ID: "XP 260",
    Developer_Name: "John Wick",
    Bug_Type: "Frontend UI",
    Bug_Sub_Type: "Fonts Size",
    Bug_Feedback: "This is Bug Feedback",
    Step_to_Reproduce: "This is Step A -> Set B",
    Ideal_Behavior: "ideal behavior",
  },
];




export const bugLength  =TableData; 
export default TableData;